### ISSUE TITLE
Error message when running after program installed

### ISSUE THREAD

**Issue by zzoozzo1122** [pldubouilh/webtorrent-webui#10]
node v6.12.3
npm v3.10.10

$ webtorrent-webui -h

/usr/lib/node_modules/webtorrent-webui/lib/handlerWebtorrent.js:131
HandlerWebtorrent.prototype.checkLocalData = async function (torrent, cb) {
                                                   ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webtorrent-webui/index.js:12:27)
root@seed3:~#

Please check.

**Comment by pldubouilh** [comment]
As specced in `package.json` you need `node >= 8` to run webtorrent webui. Node 6 doesn't support async/await.
